### PR TITLE
Sort tasks by inserted_at .

### PR DESCRIPTION
**Pull request by rhnonose**

### CODE REVIEW

**Comment by ggpasqualino** [comment]
@rhnonose @ghatighorias why is this relevant?

**Comment by rhnonose** [comment]
@ghatighorias specified 😄

**Comment by ggpasqualino** [comment]
@ghatighorias can you explain what you want to achieve?

**Comment by rhnonose** [comment]
An `order_by` link in the page will be implemented in a different PR.

**Pull request closed without merging**
