### PR TITLE
Removes the extra newline in term confirm message. center other messages

### PR DESCRIPTION
**Pull request by ghatighorias**
check comment section of this card for the description of the bug https://app.nostromo.io/work/course-planner/update-deletion-warning-messeges?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjkzNDEwLGNhcmRfdGl0bGU6dXBkYXRlLWRlbGV0aW9uLXdhcm5pbmctbWVzc2VnZXN9

### CODE REVIEW

**Comment by ghatighorias** [comment]
Anyone one knows a good solution to make sure "are you sure?" is centered ? now i did it manually

**Comment by ggpasqualino** [comment]
@ghatighorias I think there is no easy way to style the confirmation dialog.

Also, I think it would be better not to try to style it at all. 
Browsers can show the message differently and break lines in different positions.

**Comment by ghatighorias** [comment]
then shall i remove the spaces before "are you sure?"

**Comment by ggpasqualino** [comment]
@ghatighorias yeah, also make the explanation text one line

**Pull request merged**
