### PR TITLE
Makes login case insensitive

### PR DESCRIPTION
**Pull request by ghatighorias**
Check session_controller.ex line 81

And yes, for this very line i had to regenerate all the coherence controllers

### CODE REVIEW

**Comment by ghatighorias** [comment]
@rhnonose @ggpasqualino shall we cover this coherence files ? :( :( 
can't we exclude them from the coveralls

**Comment by rhnonose** [comment]
Hmm, maybe we copy coherence's tests? 😄 
I think we should ignore, but there's probably a better way.

**Comment by ggpasqualino** [comment]
https://github.com/digitalnatives/course_planner/pull/246#issuecomment-330528095

we can test it or not, excluding them is not an option in my opinion, files should only be excluded from the coverage if it doesn't make sense to test them, the files inside the the `test/support` for example

**Comment by rhnonose** [comment]
Make it a PR to generate the tests together with the code, maybe?

**Comment by ghatighorias** [comment]
@rhnonose  I don't understand

**Comment by rhnonose** [comment]
@ghatighorias Weren't the files generated by coherence?

**Comment by ghatighorias** [comment]
I am sorry @rhnonose but that will take ages, he is not responsive and apparently the controller generation function is totally changed in the new version that is about to relase

**Comment by rhnonose** [comment]
@ghatighorias I guess wen can just keep it in mind that we can use the tests in a PR later, doesn't have to be integrated first since it's a generated code.

**Comment by ghatighorias** [comment]
importing tests from coherence is hopeless. they all fail and needs to be rewritten. it's not all. the problem is that he only wrote tests for Trackable user ( one which we don't use in our app at all ).

what if I fork it, fix the issue in the fork and use my fork of coherence ? this way we don't need to deal with the coverage and test and so on

**Comment by ggpasqualino** [comment]
> what if I fork it, fix the issue in the fork and use my fork of coherence ? this way we don't need to deal with the coverage and test and so on

@ghatighorias I think that's probably better

**Pull request merged**
