### PR TITLE
Resolves all credo warnings and suggestions so far

### PR DESCRIPTION
**Pull request by ghatighorias**

### CODE REVIEW

**Comment by ghatighorias** [comment]
Please do give comments. but this PR does not need to be merge until Monday, and I can adopt my changes with latest merge on Monday too

**Comment by ggpasqualino** [comment]
could you check how to integrate credo checking into our travis-ci build?

**Comment by ggpasqualino** [comment]
💃

**Comment by ghatighorias** [comment]
Yeeeeeey

**Pull request merged**
