### PR TITLE
bug fix : no function clause matching in String.Chars.URI.to_string/1

### PR DESCRIPTION
**Pull request by ghatighorias**
Settings.get_value function should return nil in case the value saved for the setting is nil so it can use the default value

this is especially important  for url type setting with empty string. we have already save it as nil and now we should consider get_value returning the default value in case system_variable.value is equal to nil

### CODE REVIEW

**Comment by ggpasqualino** [comment]
this doesn't solve the problem completely, when the value is an empty string the problem still occurs

**Comment by ghatighorias** [comment]
i had a previous PR that for url when the string is empty it returns nil
check system_variabl.ex line 111

**Comment by ggpasqualino** [comment]
> i had a previous PR that for url when the string is empty it returns nil
exactly, it returns nil, not the default value, as far as I understood it should return the default value as well

**Comment by ggpasqualino** [comment]
@ghatighorias so I checked it out and actually the empty string will only happen when we run the seed, otherwise when we save an empty value it will be nil.

So can you change the in the seeds the value from `""` to `nil`, please?

**Pull request merged**
