### PR TITLE
Support Gigalixir and Heroku at the same time

### PR DESCRIPTION
**Pull request by jesseshieh**
I tested deploying this on my own Heroku dyno and got a login page. I also tested this on Gigalixir and got a login page. I'm not sure if everything else works, but this is promising so far. 

The only weird thing I did was I ran `heroku config:set MIX_ENV=heroku` to use the `heroku.exs` file for Heroku. Don't set it for Gigalixir.

And of course, be sure to set your `DATABASE_URL` for your Gigalixir app.

### CODE REVIEW

**Comment by ggpasqualino** [comment]
Hey @jesseshieh that's very cool!

Could you add a section in the README about setting up the app for Production using Gigalixir? something like:
- creating the app
- setting up the env variables
- deploying
- migrating the DB
- Running the seeds

**Comment by jesseshieh** [comment]
@ggpasqualino added the README.

**Comment by ggpasqualino** [comment]
@jesseshieh that's cool, thanks 😊
I will try it out, maybe I will have some questions later

**Comment by rhnonose** [comment]
Thanks @jesseshieh

**Pull request merged**
